### ISSUE TITLE
Rely on Root gun Context from Opt not Msg / Envelope

### ISSUE THREAD

**Issue by amark** [sjones6/gun-flint#1]
Lets standardize around using the opt's root gun context and not the msg/envelope, so that way I can safely in the future no longer pass `gun`.

You'd need to change **all lines** similar to:

https://github.com/sjones6/gun-flint/blob/master/src/Adapter/base-adapter.js#L57

(you get `gun` from here https://github.com/sjones6/gun-flint/blob/master/src/Adapter/base-adapter.js#L54 )

to `context.on('in'` from https://github.com/sjones6/gun-flint/blob/master/src/Adapter/base-adapter.js#L54 I think/believe.

Compare against this example:

```
Gun.on('opt', function(ctx){
	this.to.next(ctx);
	var opt = ctx.opt, no;
	if(ctx.once){ return }

	ctx.on('put', function(msg){
		this.to.next(msg);
		var err;
		Gun.graph.is(msg.put, function(node, soul){
			err = err || STORAGEwithPATCH.put(soul, node);
		});
		if(!msg['@']){ // only reply if this update isn't an ACK also.
			ctx.on('in', {'@': msg['#'], err: err, ok: err? no : 1}); // reply with ACK to msg id.
		}
	});

	ctx.on('get', function(msg){
		this.to.next(msg);
		var node, err;
		try{ node = READfromSTORAGE(msg.get['#']);
		catch(e){ err = e }
		if(node && msg.get['.']){
			node = Gun.state.to(node, msg.get['.']); // filter node down to the 1 property
		}
		ctx.on('in', {'@': msg['#'], put: Gun.graph.node(node), err: err}); // ACK the GET. 
	});
});
```

**Comment by sjones6** [comment]
Thanks for bringing this up, @amark .

Resolved with this [commit](https://github.com/sjones6/gun-flint/commit/a43800c5a751875d9c9174613a39529826592edd).
